spring.application.name=shopstack-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/shopstack_db
spring.datasource.username=postgres
spring.datasource.password=Hamsini123&&

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=TRACE

# Cloudinary Configuration
cloudinary.cloud_name=rvlkw2zp
cloudinary.api_key=364517194756456
cloudinary.api_secret=MGabpG9IhgrtKXLW6moFy3aqW_s


#razorpay config

razorpay.key.id=rzp_test_TQLSVTUTYm7AIV
razorpay.key.secret=9eTAMaQ4M0oPc8egQV0yLcwp